In [1]:
import pandas as pd
import numpy as np

In [2]:
# load & check dataset axis 0*1
books = pd.read_csv('BX-Books.csv', sep=';', error_bad_lines=False, encoding="latin-1")
books.columns = ['ISBN', 'bookTitle', 'bookAuthor', 'yearOfPublication', 'publisher', 'imageUrlS', 'imageUrlM', 'imageUrlL']
users = pd.read_csv('BX-Users.csv', sep=';', error_bad_lines=False, encoding="latin-1")
users.columns = ['userID', 'Location', 'Age']
ratings = pd.read_csv('BX-Book-ratings.csv', sep=';', error_bad_lines=False, encoding="latin-1")
ratings.columns = ['userID', 'ISBN', 'bookRating']
print(books.shape)
print(users.shape)
print(ratings.shape)

b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'
/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:27

(271360, 8)
(278858, 3)
(1149780, 3)


In [3]:
# check format of [books] dataset
books.head(3)

ISBN             bookTitle            bookAuthor yearOfPublication  \
0  0195153448   Classical Mythology    Mark P. O. Morford              2002   
1  0002005018          Clara Callan  Richard Bruce Wright              2001   
2  0060973129  Decision in Normandy          Carlo D'Este              1991   

                 publisher                                          imageUrlS  \
0  Oxford University Press  http://images.amazon.com/images/P/0195153448.0...   
1    HarperFlamingo Canada  http://images.amazon.com/images/P/0002005018.0...   
2          HarperPerennial  http://images.amazon.com/images/P/0060973129.0...   

                                           imageUrlM  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   

                                           imageUrlL  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...

In [4]:
# We do not need image urls for this project, so delete those
books.drop(['imageUrlS', 'imageUrlM', 'imageUrlL'],axis=1,inplace=True)

In [5]:
# Now check again the format
books.head(3)

ISBN             bookTitle            bookAuthor yearOfPublication  \
0  0195153448   Classical Mythology    Mark P. O. Morford              2002   
1  0002005018          Clara Callan  Richard Bruce Wright              2001   
2  0060973129  Decision in Normandy          Carlo D'Este              1991   

                 publisher  
0  Oxford University Press  
1    HarperFlamingo Canada  
2          HarperPerennial

In [6]:
# Make sure texts are fully displayed 
pd.set_option('display.max_colwidth', -1)

In [7]:
# Check data types and make changes if necessary
books.dtypes
# Note: yearOfPublication should be an integer

ISBN                 object
bookTitle            object
bookAuthor           object
yearOfPublication    object
publisher            object
dtype: object

In [8]:
# Check ISBN
books.ISBN.unique()
# books.loc[books.ISBN.isnull(),:] result shows 0 instance

array(['0195153448', '0002005018', '0060973129', ..., '006008667X',
       '0192126040', '0767409752'], dtype=object)

In [9]:
# Check bookTitle
books.bookTitle.unique()
# books.loc[books.bookTitle.isnull(),:] result shows 0 instance

array(['Classical Mythology', 'Clara Callan', 'Decision in Normandy', ...,
       'Lily Dale : The True Story of the Town that Talks to the Dead',
       "Republic (World's Classics)",
       "A Guided Tour of Rene Descartes' Meditations on First Philosophy with Complete Translations of the Meditations by Ronald Rubin"],
      dtype=object)

In [10]:
# Check bookAuthor
#books.bookAuthor.unique()
books.loc[books.bookAuthor.isnull(),:]

ISBN                                                 bookTitle  \
187689  9627982032  The Credit Suisse Guide to Managing Your Personal Wealth   

       bookAuthor yearOfPublication                       publisher  
187689  NaN        1995              Edinburgh Financial Publishing

In [11]:
books.loc[(books.ISBN == '9627982032'),'bookAuthor'] = 'unknown'
#books.loc[(books.bookTitle == 'The Credit Suisse Guide to Managing Your Personal Wealth'),:]
#books.loc[(books.publisher == 'Edinburgh Financial Publishing'),:]

In [12]:
# Check yearOfPublication
books.yearOfPublication.unique()

array([2002, 2001, 1991, 1999, 2000, 1993, 1996, 1988, 2004, 1998, 1994,
       2003, 1997, 1983, 1979, 1995, 1982, 1985, 1992, 1986, 1978, 1980,
       1952, 1987, 1990, 1981, 1989, 1984, 0, 1968, 1961, 1958, 1974,
       1976, 1971, 1977, 1975, 1965, 1941, 1970, 1962, 1973, 1972, 1960,
       1966, 1920, 1956, 1959, 1953, 1951, 1942, 1963, 1964, 1969, 1954,
       1950, 1967, 2005, 1957, 1940, 1937, 1955, 1946, 1936, 1930, 2011,
       1925, 1948, 1943, 1947, 1945, 1923, 2020, 1939, 1926, 1938, 2030,
       1911, 1904, 1949, 1932, 1928, 1929, 1927, 1931, 1914, 2050, 1934,
       1910, 1933, 1902, 1924, 1921, 1900, 2038, 2026, 1944, 1917, 1901,
       2010, 1908, 1906, 1935, 1806, 2021, '2000', '1995', '1999', '2004',
       '2003', '1990', '1994', '1986', '1989', '2002', '1981', '1993',
       '1983', '1982', '1976', '1991', '1977', '1998', '1992', '1996',
       '0', '1997', '2001', '1974', '1968', '1987', '1984', '1988',
       '1963', '1956', '1970', '1985', '1978', '1973', '1980'

In [13]:
# Check yearOfPublication
#books.publisher.unique()
books.loc[books.publisher.isnull(),:]

ISBN        bookTitle       bookAuthor yearOfPublication  \
128890  193169656X  Tyrant Moon      Elaine Corvidae  2002               
129037  1931696993  Finders Keepers  Linnea Sinclair  2001               

       publisher  
128890  NaN       
129037  NaN

In [14]:
books.loc[(books.ISBN == '193169656X'),'publisher'] = 'unknown'
books.loc[(books.ISBN == '1931696993'),'publisher'] = 'unknown'
#books.loc[(books.bookTitle == 'Finders Keepers'),:]
#books.loc[(books.bookAuthor == 'Linnea Sinclair'),:]

In [15]:
# Shown above, there are two unexpected data: DK Publishing Inc & Gallimard
books.loc[books.yearOfPublication == 'DK Publishing Inc',:]

ISBN  \
209538  078946697X   
221678  0789466953   

                                                                                                          bookTitle  \
209538  DK Readers: Creating the X-Men, How It All Began (Level 4: Proficient Readers)\";Michael Teitelbaum"          
221678  DK Readers: Creating the X-Men, How Comic Books Come to Life (Level 4: Proficient Readers)\";James Buckley"   

       bookAuthor  yearOfPublication  \
209538  2000       DK Publishing Inc   
221678  2000       DK Publishing Inc   

                                                           publisher  
209538  http://images.amazon.com/images/P/078946697X.01.THUMBZZZ.jpg  
221678  http://images.amazon.com/images/P/0789466953.01.THUMBZZZ.jpg

In [16]:
# Obviously we can see that values are placed in the wrong columns, so fix it
books.loc[books.ISBN == '078946697X','bookTitle'] = "DK Readers: Creating the X-Men, How It All Began (Level 4: Proficient Readers)"
books.loc[books.ISBN == '078946697X','bookAuthor'] = "Michael Teitelbaum"
books.loc[books.ISBN == '078946697X','yearOfPublication'] = 2000
books.loc[books.ISBN == '078946697X','publisher'] = "DK Publishing Inc"

In [17]:
books.loc[books.ISBN == '0789466953','bookTitle'] = "DK Readers: Creating the X-Men, How Comic Books Come to Life (Level 4: Proficient Readers)"
books.loc[books.ISBN == '0789466953','bookAuthor'] = "James Buckley"
books.loc[books.ISBN == '0789466953','yearOfPublication'] = 2000
books.loc[books.ISBN == '0789466953','publisher'] = "DK Publishing Inc"

In [18]:
books.loc[books.yearOfPublication == 'Gallimard',:]

ISBN  \
220731  2070426769   

                                                                       bookTitle  \
220731  Peuple du ciel, suivi de 'Les Bergers\";Jean-Marie Gustave Le Cl�©zio"   

       bookAuthor yearOfPublication  \
220731  2003       Gallimard          

                                                           publisher  
220731  http://images.amazon.com/images/P/2070426769.01.THUMBZZZ.jpg

In [19]:
books.loc[books.ISBN == '2070426769','bookTitle'] = "Peuple du ciel, suivi de 'Les Bergers"
books.loc[books.ISBN == '2070426769','bookAuthor'] = "Jean-Marie Gustave Le Cl�©zio"
books.loc[books.ISBN == '2070426769','yearOfPublication'] = 2003
books.loc[books.ISBN == '2070426769','publisher'] = "Gallimard"

In [20]:
# Now we need to redefine data type for yearOfPublication
books.yearOfPublication = pd.to_numeric(books.yearOfPublication, errors='coerce')

In [21]:
# Recheck
books.yearOfPublication.unique()

array([2002, 2001, 1991, 1999, 2000, 1993, 1996, 1988, 2004, 1998, 1994,
       2003, 1997, 1983, 1979, 1995, 1982, 1985, 1992, 1986, 1978, 1980,
       1952, 1987, 1990, 1981, 1989, 1984,    0, 1968, 1961, 1958, 1974,
       1976, 1971, 1977, 1975, 1965, 1941, 1970, 1962, 1973, 1972, 1960,
       1966, 1920, 1956, 1959, 1953, 1951, 1942, 1963, 1964, 1969, 1954,
       1950, 1967, 2005, 1957, 1940, 1937, 1955, 1946, 1936, 1930, 2011,
       1925, 1948, 1943, 1947, 1945, 1923, 2020, 1939, 1926, 1938, 2030,
       1911, 1904, 1949, 1932, 1928, 1929, 1927, 1931, 1914, 2050, 1934,
       1910, 1933, 1902, 1924, 1921, 1900, 2038, 2026, 1944, 1917, 1901,
       2010, 1908, 1906, 1935, 1806, 2021, 2012, 2006, 1909, 2008, 1378,
       1919, 1922, 1897, 2024, 1376, 2037])

In [22]:
# Dump years that are greater than 2004(dataset publication year) or equal to 0
books.loc[(books.yearOfPublication > 2004) | (books.yearOfPublication == 0),'yearOfPublication'] = np.NAN

In [23]:
# Replace these years with the average 
books.yearOfPublication.fillna(round(books.yearOfPublication.mean()), inplace=True)

In [24]:
# Recheck
print(sorted(books['yearOfPublication'].unique()))

[1376.0, 1378.0, 1806.0, 1897.0, 1900.0, 1901.0, 1902.0, 1904.0, 1906.0, 1908.0, 1909.0, 1910.0, 1911.0, 1914.0, 1917.0, 1919.0, 1920.0, 1921.0, 1922.0, 1923.0, 1924.0, 1925.0, 1926.0, 1927.0, 1928.0, 1929.0, 1930.0, 1931.0, 1932.0, 1933.0, 1934.0, 1935.0, 1936.0, 1937.0, 1938.0, 1939.0, 1940.0, 1941.0, 1942.0, 1943.0, 1944.0, 1945.0, 1946.0, 1947.0, 1948.0, 1949.0, 1950.0, 1951.0, 1952.0, 1953.0, 1954.0, 1955.0, 1956.0, 1957.0, 1958.0, 1959.0, 1960.0, 1961.0, 1962.0, 1963.0, 1964.0, 1965.0, 1966.0, 1967.0, 1968.0, 1969.0, 1970.0, 1971.0, 1972.0, 1973.0, 1974.0, 1975.0, 1976.0, 1977.0, 1978.0, 1979.0, 1980.0, 1981.0, 1982.0, 1983.0, 1984.0, 1985.0, 1986.0, 1987.0, 1988.0, 1989.0, 1990.0, 1991.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0]


In [25]:
# Redefine yearOfPublication as int32
books.yearOfPublication = books.yearOfPublication.astype(np.int32)

In [26]:
# Recheck
print(sorted(books['yearOfPublication'].unique()))

[1376, 1378, 1806, 1897, 1900, 1901, 1902, 1904, 1906, 1908, 1909, 1910, 1911, 1914, 1917, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004]


In [27]:
# Load & Check [users] dataset
print(users.shape)
users.head(3)

(278858, 3)


userID                         Location   Age
0  1       nyc, new york, usa              NaN  
1  2       stockton, california, usa        18.0
2  3       moscow, yukon territory, russia NaN

In [28]:
# Check data types
users.dtypes

userID      int64  
Location    object 
Age         float64
dtype: object

In [29]:
# Check userID
users.userID.unique()
#users.loc[users.userID.isnull(),:]

array([     1,      2,      3, ..., 278856, 278857, 278858])

In [30]:
# Check Age
users.Age.unique()

array([ nan,  18.,  17.,  61.,  26.,  14.,  25.,  19.,  46.,  55.,  32.,
        24.,  20.,  34.,  23.,  51.,  31.,  21.,  44.,  30.,  57.,  43.,
        37.,  41.,  54.,  42.,  50.,  39.,  53.,  47.,  36.,  28.,  35.,
        13.,  58.,  49.,  38.,  45.,  62.,  63.,  27.,  33.,  29.,  66.,
        40.,  15.,  60.,   0.,  79.,  22.,  16.,  65.,  59.,  48.,  72.,
        56.,  67.,   1.,  80.,  52.,  69.,  71.,  73.,  78.,   9.,  64.,
       103., 104.,  12.,  74.,  75., 231.,   3.,  76.,  83.,  68., 119.,
        11.,  77.,   2.,  70.,  93.,   8.,   7.,   4.,  81., 114., 230.,
       239.,  10.,   5., 148., 151.,   6., 101., 201.,  96.,  84.,  82.,
        90., 123., 244., 133.,  91., 128.,  94.,  85., 141., 110.,  97.,
       219.,  86., 124.,  92., 175., 172., 209., 212., 237.,  87., 162.,
       100., 156., 136.,  95.,  89., 106.,  99., 108., 210.,  88., 199.,
       147., 168., 132., 159., 186., 152., 102., 116., 200., 115., 226.,
       137., 207., 229., 138., 109., 105., 228., 18

In [31]:
# User whose age is greater than 90 or less than 5 are not considered 
users.loc[(users.Age > 90) | (users.Age < 5), 'Age'] = np.nan

In [32]:
# Replace these ages with the average
users.Age = users.Age.fillna(users.Age.mean())

In [33]:
# Redefine data type as int32
users.Age = users.Age.astype(np.int32)

In [34]:
# Recheck
print(sorted(users.Age.unique()))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]


In [35]:
# Lastly, we load & check [ratings] dataset
print(ratings.shape)
ratings.head(3)

(1149780, 3)


userID        ISBN  bookRating
0  276725  034545104X  0         
1  276726  0155061224  5         
2  276727  0446520802  0

In [36]:
# Check book rating
ratings.bookRating.unique()
# no problem with book rating data

array([ 0,  5,  3,  6,  8,  7, 10,  9,  4,  1,  2])

In [37]:
# To maintain consistency/validity for three datasets, we have to check if there are any new data in [ratings] dataset
ratings_bANDr = ratings[ratings.ISBN.isin(books.ISBN)]
ratings_uANDr = ratings[ratings.userID.isin(users.userID)]

In [38]:
# Check size for [books] & [ratings] cross dataset
ratings_bANDr.shape
# result indicating there are data loss

(1031136, 3)

In [39]:
# Check size for [users] & [ratings] cross dataset
ratings_uANDr.shape
# result indicating all users in [ratings] dataset also exist in [users] dataset

(1149780, 3)

In [40]:
# We will use [books] & [ratings] cross dataset 
ratings = ratings_bANDr

In [41]:
# Final check
ratings.shape

(1031136, 3)